name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        ref: main  # Use o branch que você deseja implantar

    - name: Configurar o Git
      run: |
        git config --global user.email "noreply@github.com"
        git config --global user.name "GitHub Actions"

    - name: Fazer Deploy no GitHub Pages
      run: |
        git add .
        git commit -m "Deploy no GitHub Pages"
        git push https://${{ secrets.workflow }}@github.com/MarceloLaurent/MarceloLaurent.git HEAD:main
